<?php

/**
 * @file
 * ZXCVBN Password Strength Estimator
 *
 */

/**
 * Password strength levels: very weak, weak, fair, good and strong.
 */
define('ZXCVBN_PASSWORD_STRENGTH_VERY_WEAK', 0);
define('ZXCVBN_PASSWORD_STRENGTH_WEAK', 1);
define('ZXCVBN_PASSWORD_STRENGTH_FAIR', 2);
define('ZXCVBN_PASSWORD_STRENGTH_GOOD', 3);
define('ZXCVBN_PASSWORD_STRENGTH_STRONG', 4);

/**
 * Implements hook_autoload_info().
 */
function zxcvbn_autoload_info() {
  return array(
    'ZxcvbnPhp\Zxcvbn' => 'includes/zxcvbn-php/src/Zxcvbn.php',
    'ZxcvbnPhp\TimeEstimator' => 'includes/zxcvbn-php/src/TimeEstimator.php',
    'ZxcvbnPhp\Scorer' => 'includes/zxcvbn-php/src/Scorer.php',
    'ZxcvbnPhp\Matcher' => 'includes/zxcvbn-php/src/Matcher.php',
    'ZxcvbnPhp\Feedback' => 'includes/zxcvbn-php/src/Feedback.php',
    // Math
    // interface
    'ZxcvbnPhp\Math\BinomialProvider' => 'includes/zxcvbn-php/src/Math/BinomialProvider.php',
    'ZxcvbnPhp\Math\Binomial' => 'includes/zxcvbn-php/src/Math/Binomial.php',
    // Impl
    // abstract class
    'ZxcvbnPhp\Math\Impl\AbstractBinomialProvider' => 'includes/zxcvbn-php/src/Math/Impl/AbstractBinomialProvider.php',
    'ZxcvbnPhp\Math\Impl\AbstractBinomialProviderWithFallback' => 'includes/zxcvbn-php/src/Math/Impl/AbstractBinomialProviderWithFallback.php',
    // classes
    'ZxcvbnPhp\Math\Impl\BinomialProviderFloat64' => 'includes/zxcvbn-php/src/Math/Impl/BinomialProviderFloat64.php',
    'ZxcvbnPhp\Math\Impl\BinomialProviderInt64' => 'includes/zxcvbn-php/src/Math/Impl/BinomialProviderInt64.php',
    'ZxcvbnPhp\Math\Impl\BinomialProviderPhp73Gmp' => 'includes/zxcvbn-php/src/Math/Impl/BinomialProviderPhp73Gmp.php',
    // Matchers
    // interface
    'ZxcvbnPhp\Matchers\MatchInterface' => 'includes/zxcvbn-php/src/Matchers/MatchInterface.php',
    // abstract class
    'ZxcvbnPhp\Matchers\BaseMatch' => 'includes/zxcvbn-php/src/Matchers/BaseMatch.php',
    // classes
    'ZxcvbnPhp\Matchers\Bruteforce' => 'includes/zxcvbn-php/src/Matchers/Bruteforce.php',
    'ZxcvbnPhp\Matchers\DateMatch' => 'includes/zxcvbn-php/src/Matchers/DateMatch.php',
    'ZxcvbnPhp\Matchers\DictionaryMatch' => 'includes/zxcvbn-php/src/Matchers/DictionaryMatch.php',
    'ZxcvbnPhp\Matchers\L33tMatch' => 'includes/zxcvbn-php/src/Matchers/L33tMatch.php',
    'ZxcvbnPhp\Matchers\RepeatMatch' => 'includes/zxcvbn-php/src/Matchers/RepeatMatch.php',
    'ZxcvbnPhp\Matchers\ReverseDictionaryMatch' => 'includes/zxcvbn-php/src/Matchers/ReverseDictionaryMatch.php',
    'ZxcvbnPhp\Matchers\SequenceMatch' => 'includes/zxcvbn-php/src/Matchers/SequenceMatch.php',
    'ZxcvbnPhp\Matchers\SpatialMatch' => 'includes/zxcvbn-php/src/Matchers/SpatialMatch.php',
    'ZxcvbnPhp\Matchers\YearMatch' => 'includes/zxcvbn-php/src/Matchers/YearMatch.php',
  );
}

/**
 * Implements hook_menu().
 */
function zxcvbn_menu() {
  $items['zxcvbn-password-strength'] = array(
    'title' => 'Password strength feedback',
    'page callback' => 'zxcvbn_password_strength_feedback',
    'delivery callback' => 'backdrop_json_deliver',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );

  return $items;
}

/**
 * Implements hook_element_info_alter().
 */
function zxcvbn_element_info_alter(&$type) {
  if (isset($type['password']['#process'])) {
    $type['password']['#process'] = array('ajax_process_form', 'zxcvbn_form_process_password');
  }
  if (isset($type['password_confirm']['#process'])) {
    $type['password_confirm']['#process'] = array('form_process_password_confirm', 'zxcvbn_form_process_password_confirm');
  }
}

/**
 * Form element process handler for client-side password hide/show and strength.
 *
 * @param array $element
 *   The form element to process.
 * @param array $form_state
 *   The $form_state array of the form this element belongs to.
 */
function zxcvbn_form_process_password($element, $form_state = array()) {
  global $user;

  if ($element['#password_strength']) {
    if (isset($form_state['user']) && is_a($form_state['user'], 'User')) {
      // Existing account, not the current user if an admin edits an account.
      $username = $form_state['user']->name;
      $email = $form_state['user']->mail;
    }
    else {
      // The AnonymousUser object has no mail property, and name is NULL.
      // The User object has both mail and name set.
      $username = (isset($user->name) ? $user->name : '');
      $email = (isset($user->mail) ? $user->mail : '');
    }
    $strength_settings = array(
      'threshold' => settings_get('zxcvbn_password_strength_threshold', 2),
      'scores' => array(
        ZXCVBN_PASSWORD_STRENGTH_VERY_WEAK => 'weak',
        ZXCVBN_PASSWORD_STRENGTH_WEAK => 'weak',
        ZXCVBN_PASSWORD_STRENGTH_FAIR => 'fair',
        ZXCVBN_PASSWORD_STRENGTH_GOOD => 'good',
        ZXCVBN_PASSWORD_STRENGTH_STRONG => 'strong',
      ),
      'labels' => array(
        'strengthTitle' => t('Password strength: '),
        ZXCVBN_PASSWORD_STRENGTH_VERY_WEAK => t('very weak'),
        ZXCVBN_PASSWORD_STRENGTH_WEAK => t('weak'),
        ZXCVBN_PASSWORD_STRENGTH_FAIR => t('fair'),
        ZXCVBN_PASSWORD_STRENGTH_GOOD => t('good'),
        ZXCVBN_PASSWORD_STRENGTH_STRONG => t('excellent'),
      ),
      'data' => array(
        'username' => $username,
        'email' => $email,
      ),
    );

    $element['#attributes']['data-password-strength'] = backdrop_json_encode($strength_settings, FALSE);
  }

  if ($element['#password_toggle']) {
    $toggle_settings = array(
      'toggleShowTitle' => t('Show password'),
      'toggleHideTitle' => t('Hide password'),
      'toggleDefault' => $element['#password_shown'] ? 'show' : 'hide',
    );

    $element['#attributes']['data-password-toggle'] = backdrop_json_encode($toggle_settings, FALSE);
  }

  if ($element['#password_strength'] || $element['#password_toggle']) {
    $element['#attached']['js'][] = backdrop_get_path('module', 'zxcvbn') . '/js/user.js';
  }
  return $element;
}

/**
 * Form element process handler for client-side password validation.
 *
 * This #process handler is automatically invoked for 'password_confirm' form
 * elements to add the JavaScript and string translations for dynamic password
 * validation.
 *
 * @see system_element_info()
 */
function zxcvbn_form_process_password_confirm($element) {
  $confirm_settings = array(
    'confirmTitle' => t('Passwords match: '),
    'confirmSuccess' => t('yes'),
    'confirmFailure' => t('no'),
  );

  $element['#attached']['js'][] = backdrop_get_path('module', 'zxcvbn') . '/js/user.js';
  $element['pass2']['#attributes']['data-password-confirm'] = backdrop_json_encode($confirm_settings, FALSE);

  return $element;
}

/**
 * Implements hook_form_alter().
 *
 * @see user_account_form()
 * @see user_pass_reset_form()
 * @see user_profile_form()
 * @see user_register_form()
 * @see user_form_process_password()
 * @see user_admin_settings()
 */
function zxcvbn_form_alter(&$form, &$form_state, $form_id) {
  $form_ids = [
    'user_account_form',
    'user_pass_reset_form',
    'user_profile_form',
    'user_register_form',
    'user_form_process_password',
    'user_admin_settings',
  ];
  if (in_array($form_id, $form_ids)) {
    $help = _zxcvbn_password_policy_help();

    // Replace validation which is enabled if a user is required to provide a
    // strong password.
    $reject_weak_passwords = config_get('system.core', 'user_password_reject_weak');
    if ($reject_weak_passwords && in_array('user_password_policy_validate', $form['#validate'])) {
      // Add own validation instead.
      $form['#validate'] = array_filter($form['#validate'], static function ($element) {
        return $element !== 'user_password_policy_validate';
      });
      $form['#validate'][] = 'zxcvbn_password_policy_validate';

      // Rely on dynamic instead of static feedback.
      if (isset($form['account']['pass']['#description'])) {
        $form['account']['pass']['#description'] = '';
      }
      if (isset($form['pass']['#description'])) {
        $form['pass']['#description'] = '';
      }
    }

    if (isset($form['password_policy']['user_password_reject_weak']['#description'])) {
      $form['password_policy']['user_password_reject_weak']['#description'] = $help;
    }
  }
}

/**
 * Validation callback for password constraints.
 *
 * @see user_account_form()
 * @see user_pass_reset_form()
 */
function zxcvbn_password_policy_validate($form, &$form_state) {
  $strength = 0;
  if (!array_key_exists('pass', $form_state['values'])) {
    // If mail verification is required, user registration forms don't have a
    // password field.
    return;
  }
  $password = trim($form_state['values']['pass']);

  if ($form['#form_id'] == 'user_profile_form' && strlen($password) == 0) {
    // On profile form and no new password has been set.
    return;
  }
  if ($form['#form_id'] == 'user_pass_reset_form') {
    $account = $form['#account'];
    $username = $account->name;
    $email = $account->mail;
  }
  else {
    $username = $form_state['values']['name'];
    $email = $form_state['values']['mail'];

    $user_input = [
      'username' => $username,
      'email' => $email,
    ];
    foreach ($form_state['values'] as $key => $value) {
      if (strpos($key, 'field_') !== FALSE) {
        foreach ($value as $languages) {
          foreach ($languages as $item) {
            // Include field types that have a value.
            // @todo include other field types.
            if (isset($item['value'])) {
              $user_input[] = $item['value'];
            }
          }
        }
      }
    }
  }

  $strength = _zxcvbn_password_evaluate_strength($password, $user_input);

  if ($strength['score'] < settings_get('zxcvbn_password_strength_threshold', 2)) {
    $warning = $strength['feedback']['warning'] ? $strength['feedback']['warning'] . '.' : '';
    $suggestions = $strength['feedback']['suggestions'] ? 'Consider:' . theme('item_list', ['items' => $strength['feedback']['suggestions'], 'type' => 'ul']) : '';
    form_set_error('complex_pass', t('The password is too weak. @warning !suggestions', ['@warning' => $warning, '!suggestions' => $suggestions]));
  }

  if (backdrop_strtolower($password) == backdrop_strtolower($username)) {
    form_set_error('username_pass', t('The password cannot be the same as the username.'));
  }
  if (backdrop_strtolower($password) == backdrop_strtolower($email)) {
    form_set_error('email_pass', t('The password cannot be the same as the email.'));
  }
}

/**
 * AJAX callback
 *
 * @return array
 *   Returned as JSON via backdrop_json_delivery
 */
function zxcvbn_password_strength_feedback() {
  $strength = [];
  if (!empty($_POST['passwordInput'])) {
    $settings = $_POST['passwordStrengthSettings'];
    $strength = _zxcvbn_password_evaluate_strength($_POST['passwordInput'], [
      'username' => $settings['data']['username'],
      'email' => $settings['data']['email'],
    ]);
  }
  return $strength;
}

/**
 * Evaluate password strength
 *
 * @param string $password
 * @param array $user_input
 *   An array of username, email and other user input. The strings are taken
 *   into account in the algorithm.
 *
 * @return array
 *   An array including:
 *     - score: An integer representing password strength.
 *     - feedback
 */
function _zxcvbn_password_evaluate_strength($password, $user_input) {
  $zxcvbn = new ZxcvbnPhp\Zxcvbn();
  $warning = '';
  if (isset($user_input['username']) && backdrop_strtolower($password) == backdrop_strtolower($user_input['username'])) {
    $warning = t('The password cannot be the same as the username');
  }
  if (isset($user_input['email']) && backdrop_strtolower($password) == backdrop_strtolower($user_input['email'])) {
    $warning = t('The password cannot be the same as the email');
  }
  $strength = [
    'score' => 0,
    'feedback' => [
      'warning' => $warning,
      'suggestions' => [],
    ]
  ];
  if (!$warning) {
    $strength = $zxcvbn->passwordStrength($password, array_values($user_input));
  }
  return $strength;
}

/**
 * Generates help text for core password constraints on forms.
 *
 * @see user_account_form()
 */
function _zxcvbn_password_policy_help() {
  // Label the threshold for the password description.
  $strength_threshold = settings_get('zxcvbn_password_strength_threshold', 2);

  if ($strength_threshold < ZXCVBN_PASSWORD_STRENGTH_FAIR) {
    $threshold_label = array('weak' => t('weak'));
  }
  elseif ($strength_threshold < ZXCVBN_PASSWORD_STRENGTH_GOOD) {
    $threshold_label = array('fair' => t('fair'));
  }
  elseif ($strength_threshold < ZXCVBN_PASSWORD_STRENGTH_STRONG) {
    $threshold_label = array('good' => t('good'));
  }
  else {
    $threshold_label = array('strong' => t('excellent'));
  }

  $criteria = array();
  $criteria[] = t('The password cannot be the same as the username or email address.');
  $criteria[] = t('The password is stronger if it does not include any common patterns like dates, repeating characters, sequences, and keyboard patterns.');
  $criteria[] = t('The password is stronger if it does not include commonly-used passwords, common American names and surnames, nor common English words.');

  $help = '<div class="password-strength-help-text ' . key($threshold_label) . '">' . t('The password strength indicator must be %threshold or better.', array('%threshold' => current($threshold_label)));
  $help .= ' ' . t('The password strength will be estimated via <a href="@url">Zxcvbn</a> and custom criteria:', ['@url' => 'https://github.com/bjeavons/zxcvbn-php']) . '</div>' . theme('item_list', array('items' => $criteria, 'type' => 'ul'));

  return $help;
}
